# Springboot 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yuc?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456

server:
  port: 8089

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
